#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_LINES 10
#define LINE_LENGTH 25
#define MAX_SERVER_NAME 20
#define IP_ADDR_MAX_LEN 16
#define MAX_RECORDS 10000
#define HASH_MAP_SIZE 100
#define KEY_SIZE 5
#define VAL_SIZE 5
#define MAX_MSG_SIZE 1024
#define MAX_QUEUE_CAPACITY 1000

#define MAX_SHUFFLE_SIZE 100
#define MAX_REQ_IN_FLIGHT 5
#define MAX_REPLY_SIZE 2 

#endif
