/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message_formats.proto */

#ifndef PROTOBUF_C_message_5fformats_2eproto__INCLUDED
#define PROTOBUF_C_message_5fformats_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _OpenMessage OpenMessage;


/* --- enums --- */


/* --- messages --- */

struct  _OpenMessage
{
  ProtobufCMessage base;
  int32_t block_size;
};
#define OPEN_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&open_message__descriptor) \
    , 0 }


/* OpenMessage methods */
void   open_message__init
                     (OpenMessage         *message);
size_t open_message__get_packed_size
                     (const OpenMessage   *message);
size_t open_message__pack
                     (const OpenMessage   *message,
                      uint8_t             *out);
size_t open_message__pack_to_buffer
                     (const OpenMessage   *message,
                      ProtobufCBuffer     *buffer);
OpenMessage *
       open_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   open_message__free_unpacked
                     (OpenMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*OpenMessage_Closure)
                 (const OpenMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor open_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_message_5fformats_2eproto__INCLUDED */
