#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_LINES 10
#define LINE_LENGTH 25
#define MAX_SERVER_NAME 20
#define IP_ADDR_MAX_LEN 16
#define MAX_RECORDS 100000
#define HASH_MAP_SIZE 100
#define KEY_SIZE 16
#define VAL_SIZE 16
#define MAX_MSG_SIZE 16384
#define MAX_QUEUE_CAPACITY 1000
#define MAX_CHUNK_REQ_SIZE 2

// REDUCER CONFIG
#define MAX_SHUFFLE_SIZE 52
#define MAX_REQ_IN_FLIGHT 4

// MAPPER CONFIG
#define MAX_REPLY_SIZE 320

// TO BE SET ON MAPPER
// PER_REQUEST_SIZE = ((KEY_SIZE + VAL_SIZE) * MAX_REPLY_SIZE)

// TO BE SET ON RECEIVER
// MAX_SHUFFLE_SIZE 
#endif
