/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message_formats.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message_formats.pb-c.h"
void   open_message__init
                     (OpenMessage         *message)
{
  static const OpenMessage init_value = OPEN_MESSAGE__INIT;
  *message = init_value;
}
size_t open_message__get_packed_size
                     (const OpenMessage *message)
{
  assert(message->base.descriptor == &open_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t open_message__pack
                     (const OpenMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &open_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t open_message__pack_to_buffer
                     (const OpenMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &open_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpenMessage *
       open_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpenMessage *)
     protobuf_c_message_unpack (&open_message__descriptor,
                                allocator, len, data);
}
void   open_message__free_unpacked
                     (OpenMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &open_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor open_message__field_descriptors[1] =
{
  {
    "block_size",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OpenMessage, block_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_message__field_indices_by_name[] = {
  0,   /* field[0] = block_size */
};
static const ProtobufCIntRange open_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor open_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "open_message",
  "OpenMessage",
  "OpenMessage",
  "",
  sizeof(OpenMessage),
  1,
  open_message__field_descriptors,
  open_message__field_indices_by_name,
  1,  open_message__number_ranges,
  (ProtobufCMessageInit) open_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
